<a href="https://colab.research.google.com/github/Ignacio737/PrimerProyectoFisica/blob/master/SeriePythonBasico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Serie Python 
### Temas básicos de python.

Las indicaciones son editar este archivo, deje casillas de código para que sea de la manera más ordenada posible, una vez que estén sus funciones deben subir a classroom el ipynb y generar un pdf de el mismo. 

**TODAS LAS CASILLLAS DEBEN ESTAR EJECUTADAS**

Muchos incisos implican inputs del usuario, ustedes deben probar cada una de sus funciones (ingresar los valores que se pidan) para mandarme el archivo ipynb y el pdf una vez que hayan ejecutado todo para que vea los outputs de sus programas. En caso de que no lo hagan de esa manera y lo manden sin ejecutar tendrán un **punto menos** en la serie.



Mi recomendación personal es que una vez que tengan su serie lista reinicien el kernel y ejecuten todo así podrán probar que todo este correcto antes de enviarlo.


No considero que sea una serie dificil, el fin es sólo que práctiquen. Hay muchas cosas que pueden hacerse en una línea si investigan sobre funciones que ya están implementadas en python. 

Si lo hacen de ambas maneras tendrán un punto extra y si comentan todo su código pueden tener otro punto extra.


Cualquier duda o complicación comuniquense conmigo.


Saludos.

In [0]:
print("EJEMPLO:")
input("Está casilla ha sido ejecutada por: ")

EJEMPLO:
Está casilla ha sido ejecutada por: Ignacio


'Ignacio'

1) Crea una lista que regrese los multiplos de 7 y números que lleven algún siete en sus cifra hasta el 700. 

    [Out]: [7, 14, 17, 21, 27, 28, 35, 37, ...]

2) Realiza una función que reciba un número y regrese dicho número elevado por un número aleatorio entero entre el 1 y el 10

In [0]:
from random import uniform #biblioteca aleatoria, funciones uniform, radint(numero aleatorios enteroes)
numero=float(input("Escribe un numero:"))
def Cuadrado(numero):
    potencia= numero**3
    print(potencia)
    return
print(Cuadrado(numero))

Escribe un numero:5
125.0
None


3) Crea una función que reciba dos números e indique si son múltiplos el uno del otro 

In [0]:
numero1=int(input("Escribe el primer numero:"))
numero2=int(input("Escribe el segundo numero:"))
def Multiplos(numero1,numero2):
    if numero1%numero2==0 or numero2%numero1==0:
       print("son multiplos")
    else: 
      print("no son multiplos")
print(Multiplos(numero1,numero2))


Escribe el primer numero:5
Escribe el segundo numero:10
son multiplos
None


4) Crea una función que reciba una lista desordenada de números y la ordene de mayor a menor

    Ejemplo: [In]: [77, 1, 364, 587, 21, 13, 54, 999]  [Out]: [999, 587, 364, 77, 54, 21, 13, 1]

In [0]:
lista= (1,20,6,12,5) #investigar funciones predeterminadas,buscar foros, paginas oficiales de Python
for recorrido in range(1,len(lista)):
   for posicion in range(len(lista)-recorrido):
       if lista(posicion) > lista(posicion+1):
         temp=lista(posicion)
         lista(posicion)=lista(posicion+1)
         lista(posicion+1)=temp
print(lista)

SyntaxError: ignored

5) Teniendose una lista con números entre el uno y el diez que pueden o no estar repetidos realiza un programa que pueda regresar el número que no está repetido de cualquier lista de este tipo.

    Ejemplo: [In]: [ 1, 1, 2, 2, 3, 4, 4, 5, 5, 6, 6, 7, 7]  [Out]: 3

In [16]:
lista=[ 1, 1, 2, 2, 3, 4, 4, 5, 5, 6, 6, 7, 7] 
for elemento in lista:
    if lista.count(elemento) == 1:
       print(elemento)






3


6) Implementa una función que reciba una lista de números enteros entre el uno y el diez que pueden o no estar repetidos y regrese un diccionario cuya clave sea el número (de menor a mayor) y el valor el número de veces que se repite ese item en la lista.

      Ejemplo: [In]:[1, 8, 9, 6, 4, 1, 1, 5, 4, 2, 3, 5, 5, 8, 1, 3, 2] 
               [Out]: { 1:4 , 2:2 , 3:2, 4:2, 5:3, 6:1, 8:2, 9:1} 

**NOTA**: Consideren que la lista sólo va de 1 al 10 así que pueden evaluar primero los valores dentro de la lista o evaluar del 1 al 10 con lo que obtendrían: { 1:4 , 2:2 , 3:2, 4:2, 5:3, 6:1, 7:0, 8:2, 9:1, 10:0 }

In [13]:
pruebaLista=[1, 8, 9, 6, 4, 1, 1, 5, 4, 2, 3, 5, 5, 8, 1, 3, 2] 
def contadorRepeticiones(lista):
    diccionarioRepeticiones = { numero:lista.count(numero) for numero in set(lista)}
    return diccionarioRepeticiones
print(contadorRepeticiones(pruebaLista))    

{1: 4, 2: 2, 3: 2, 4: 2, 5: 3, 6: 1, 8: 2, 9: 1}


7) Elabora una función que reciba valores del usuario y los añada a una lista con la condición de que sea un valor númerico entre el 0 y 10.  

**OPCIONAL +1 punto en la serie**: En caso de que no sea un valor númerico que levante <raise> una excepción creada por ustedes que se llamen "aquí no"

In [23]:
def agregarEntreUnoDiez():
    lista:[] 
    respuesta=' '
    while respuesta !='si ':
        try:
            print("ingresa el numero a tratar")
            numeroIngresado=float(input())
            if 0 <= numeroIngresado <= 10:
                lista.append(numeroIngresado)
        except ValueError:
            print("Aqui no")
        finally:
            print("Para segui intentando teclea 'si ', en caso contrario teclea 'no '")
            resultado=input()
            if resultado == 'no ':
               break 
    print(lista)
agregarEntreUnoDiez()

ingresa el numero a tratar
4
Para segui intentando teclea 'si ', en caso contrario teclea 'no '
no


UnboundLocalError: ignored

8) Haz una función que reciba una frase y regrese un booleano True en caso de ser palindromo y False de no serlo.

    Ejemplo: [In]: "Anita lava la tina"  [Out]: True
    
**NOTA**: Tomen en cuenta que los espacios no deben ser tomados en cuenta y que Python es sensible a mayúsculas y minúsculas.

In [25]:
def identificadorPalindromos(cadenaInicial):
    cadenaMinuscula=cadenaInicial.lower()
    cadenaSinEspacios=cadenaMinuscula.replace(' ',' ')
    cadenainvertida=CadenaSinEspacios[::-1]
    return cadenaSinEspacios==cadenaInvertida
pruebaCadena = 'Anita lava la tina '
print(identificadorPalindromos(pruebaCadena))

NameError: ignored

9) Escribe una función que reciba una cadena y regrese un diccionario donde la llave sea la vocal y el valor el número de veces que aparece en dicha cadena. 

    Ejemplo: [In]: "Parangaricutirimicuaro"   [Out]: { 'a':4, 'e':0, 'i':4, 'o':1, 'u':2 }

In [29]:
def contadorVocales(cadena):
    diccionarioVocales= {vocal:cadena.count(vocal) for vocal in ['a ','e ',' i ',' o','u ']}
    return diccionarioVocales
cadenaPrueba="Desestresante"
print(contadorVocales(cadenaPrueba))

{'a ': 0, 'e ': 0, ' i ': 0, ' o': 0, 'u ': 0}


8) Realiza una función que al ingresar tu altura y tu peso regrese tu índice de masa corporal(IMC)
    
**NOTA**: IMC= peso en kg / estatura en metros al cuadrado

In [33]:
print('Ingresa tu peso: ')
peso=float(input())
print(' Ingresa tu estatura:')
estatura=float(input())

def calcularIMC(peso,altura):
    return peso/estatura**2

print('Tu indice de masa coorporal es',calcularIMC(peso,estatura))

Ingresa tu peso: 
70
 Ingresa tu estatura:
1.73
Tu indice de masa coorporal es 23.38868655818771


9) Elabora un programa que permita realizar la suma de dos matrices 3x3. Los datos de ambas matrices deberán ser ingresados por el usuario.

**NOTA** : Las matrices en python puede implementarse con listas dentro de listas

10) Con ayuda de las sentencias if y elif elabora una calculadora que permita sumar, restar, multiplicar y dividir dos números. El usuario podrá elegir qué operación desea realizar e ingresar dichos dos números.

In [37]:
print("Ingrese el primer numero")
primerNumero=float(input())
print("Ingrese el segundo numero")
segundoNumero=float(input())
print("Operacion que deseas realiza: *,/,+ ")
orden=input()
if orden==' +':
  print(primerNumero+segundoNumero)
elif orden=='* ':
  print(primerNumero*segundoNumero)
if orden==' /':
  print(primerNumero/segundoNumero)

Ingrese el primer numero
50
Ingrese el segundo numero
10
Operacion que deseas realiza: *,/,+ 
/


11) Implementando funciones lamba, elabora un programa que permita realizar las operaciones básicas aritméticas

In [41]:
print('Ingresa un numero: ')
primernumero=float(input())
print(' Ingresa otro numero:')
segundonumero=float(input( ))
suma=lambda primersumando, segundosumando: primersumando + segundosumando
print('La suma es: ',suma(primernumero,segundonumero))
resta= lambda primersumando, segundosumando: primersumando - segundosumando
print('La resta es: ', resta(primernumero,segundonumero))
producto=lambda primersumando,segundosumando: primersumando * segundosumando
print('El producto es: ', producto(primernumero,segundonumero))

Ingresa un numero: 
8
 Ingresa otro numero:
5
La suma es:  13.0
La resta es:  3.0
El producto es:  40.0


12) Haz una función que regrese los números primos menores de 50

    Ejemplo: [Out]: [ 1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 47]

In [49]:
lista:[ 1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 47]
def primM50(lista):
    
    for num in range(2,50):
        for i in range(2,num):
            if (num % i)== 0:
              break
        else:
           lista.append(num)
    return lista
print(primM50(lista))

[1, 1, 2, 2, 3, 4, 4, 5, 5, 6, 6, 7, 7, 2, 2, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


13) Realiza una función donde ingreses un número "n" y que regrese "n" términos de la serie fibonacci
    
    Ejemplo: [In]: 11 [Out]: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55 ]

In [53]:
def fibonacci(n):
    def fibonachear(num):
        if num < 2:
           return num
        else:
            return fibonachear(num-1) + fibonachear(num-2)
    listaFibonacci= []
    for numero in range(n):
        listaFibonacci.append(fibonachear(numero))
    print(listaFibonacci)

fibonacci(5)

[0, 1, 1, 2, 3]


14) Escribe una función que pida un número "n" y luego pida al usuario "n" número de entradas

In [60]:
def salida():
    lista=[]
    print("Ingresa un numero entero")
    n=int(input())
    for i in range(n):
        print("Ingresa entrada",i+1)
        entrada=input()
        lista.append(entrada)
    return print(lista)
salida()


Ingresa un numero entero
3
Ingresa entrada 1
4
Ingresa entrada 2
6
Ingresa entrada 3
7
['4', '6', '7']


15) Realiza una función que reciba una matriz 3x3 y regresé la transpuesta de dicha matriz

In [64]:
import numpy as np 
matrizPrueba=np.matrix([[4,6,7],[5,8,9,],[0,0,0]])
def inversa(matriz):
    invertir= matriz*(-1)
    return invertir
print(inversa(matrizPrueba))

[[-4 -6 -7]
 [-5 -8 -9]
 [ 0  0  0]]


16) Crea una lista con los números del 1 al 100 que en los multiplos de 7 y números que lleven algún siete en sus cifra regrese la cadena "Aplauso"

    Ejemplo: [Out]: [1, 2, 3, 4, 5, 6, "Aplauso", 8, 9, 10, 11, 12, 13, "Aplauso", 15, 16, "Aplauso", 18, 19, 20, "Aplauso", 22, 23, 24, 25, 26,"Aplauso", "Aplauso", 29, 30, 31, 32, 33, 34, "Aplauso", 36, "Aplauso", 38, 39, 40, 41, "Aplauso", 43, 44, 45, 46, "Aplauso", 48, "Aplauso", 50, 51, 52, 53, 54, 55, "Aplauso", "Aplauso", 58, 59, 60, 61, 62, "Aplauso", 64, 65, 66, "Aplauso", 68, 69, "Aplauso", "Aplauso", "Aplauso", "Aplauso", "Aplauso", "Aplauso", "Aplauso", "Aplauso", "Aplauso", "Aplauso", 80, 81, 82, 83, "Aplauso", 85, 86, "Aplauso", 88, 89, 90, "Aplauso", 92, 93, 94, 95, 96, "Aplauso", "Aplauso", 99, 100]

In [67]:
listaEvitaSiete=[]
for numero in range(1,100)
    if numero% 7==0 or '7' in str(numero):
       listaEvitaSiete.append('Aplauso')
    else: 
      listaEvitaSiete.append(numero)
print(listaEvitaSiete)

SyntaxError: ignored

17) Haz una función que reciba un número "n" pueda crear una lista del 1 al 100 que regrese la cadena "NO" para los números divisibles entre el número "n"

    Ejemplo: [In]: 15 [Out]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, "NO" , 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, "NO", 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, "NO", 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, "NO", 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, "NO", 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, "NO", 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]

18) Dada una lista con elementos númericos del 1 al 100 elabora una lista por comprensión que guarde los elementos que son múltiplos de 5.

19) Escribe una función que tome un entero positivo "n" y regrese la suma de los cuadrados de todos los números pares menores o iguales que "n"

    Ejemplo: [In]: 12 [Out]: 364
    

19) Realiza una función que pida un número "n" y elabora un menú donde el usuario pueda elegir si quiere convertir  n a base binaria, hexadecimal u octal.

    Ejemplo suponiendo que se elige hexadecimal: [In]: 365 [Out]: 16d
    
**NOTA**: Pueden realizar la función desde 0 lo cuál les daría su punto extra o investiguen los métodos hex(), bin(),....

20) En esta opción eres libre de poner cualquier función. Debes comentar que es lo que hace

**NOTA**: No, no puede ser sólo un print. 

**NOTA**: No, tampoco cuenta hacer dos o tres prints. 

**NOTA**: Deben usar aunque sea un bucle, sean creativos. 